version: '3'

services:
  blog_postgresql:
    image: postgres:12
    container_name: blog_postgresql
    volumes: 
      - blog_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports: 
      - "5432:5432"
    networks:
      - blogpy_network

volumes: 
    blog_postgresql:
      external: true
networks:
    blogpy_network:
      external: true